  version: '3.8'

  services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - NODE_ENV=production
        - PORT=5003
        - DB_HOST=183.90.173.149
        - DB_PORT=3306
        - DB_USER=db-user
        - DB_PASSWORD=Kurifatto300#
        - DB_NAME=DB-Default
        - JWT_SECRET=asdfghjkl;;lkjhgfdsa
        - JWT_EXPIRES_IN=7d
      ports:
        - "5003:5003"
      # volumes:
      #   - ./backend:/app
      #   - /app/node_modules
      networks:
        - nipa-travel-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
        interval: 30s
        timeout: 10s
        retries: 3

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      environment:
        - NEXT_PUBLIC_API_BASE_URL=http://backend:5003/
        - NEXT_PUBLIC_API_VERSION=v1
        - NEXT_PUBLIC_APP_NAME=NIPA Frontend
        - NEXT_PUBLIC_APP_VERSION=1.0.0
        - NODE_ENV=production
      ports:
        - "3000:3000"
      # volumes:
      #   - ./frontend:/app
      #   - /app/node_modules
      #   - /app/.next
      depends_on:
        - backend
      networks:
        - nipa-travel-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
        interval: 30s
        timeout: 10s
        retries: 3

  networks:
    nipa-travel-network:
      driver: bridge
