version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5003
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=db-user
      - DB_PASSWORD=Kurifatto300#
      - DB_NAME=DB-Default
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nipa-travel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./nipa-travel-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5003
    volumes:
      - ./nipa-travel-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - nipa-travel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nipa-travel-network:
    driver: bridge