services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    # image: nipa-travel-frontend
    container_name: nipa-travel-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nipa-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: nipa-travel-backend
    container_name: nipa-travel-backend
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8000:8000"
    networks:
      - nipa-network
    restart: unless-stopped

networks:
  nipa-network:
    driver: bridge
